---
output: html_document
---
---
title: "MEP-LINCS `r x[["CellLine"]]` `r x[["StainingSet"]]` `r x[["Signal"]]`  SVD Analysis"
date: "`r Sys.Date()`"
---

```{r global_options_Setup, include=FALSE}
#Author: Mark Dane, copyright 2015
knitr::opts_chunk$set(fig.width=12, fig.height=8,
                      echo=FALSE, warning=FALSE, message=FALSE)

#source("MEPLINCSFunctions.R")

library("ggplot2")
library("reshape2")
library("data.table")
library("limma")
library("MEMA")
library("grid")
library("knitr")
library("gplots")
library("RColorBrewer")
library("RUVnormalize")

#Read in file based on name in dataframe
l1 <- fread(x[["inputFileName"]], showProgress = FALSE)

#Keep the control wells separate
l1$Ligand[l1$Ligand=="FBS"] <- paste(l1$Ligand[l1$Ligand=="FBS"],"C",as.numeric(factor(l1$Barcode[l1$Ligand=="FBS"])),sep="")
l1$MEP <- paste(l1$ECMp,l1$Ligand,sep="_")

#Delete the fiducial and blank spots
setkey(l1, "ECMp")
l1 <- l1[!"fiducial"]
l1 <- l1[!"blank"]

#Logit transform DNA2NProportion
#logit(p) = log[p/(1-p)]
DNA2NImpute <- l1$Nuclei_PA_Cycle_DNA2NProportion
DNA2NImpute[DNA2NImpute==0] <- .01
DNA2NImpute[DNA2NImpute==1] <- .99
l1$Nuclei_PA_Cycle_DNA2NProportionLogit <- log2(DNA2NImpute/(1-DNA2NImpute))

#logit transform eccentricity
EccImpute <- l1$Nuclei_CP_AreaShape_Eccentricity
EccImpute[EccImpute==0] <- .01
EccImpute[EccImpute==1] <- .99
l1$Nuclei_PA_AreaShape_EccentricityLogit <- log2(EccImpute/(1-EccImpute))

#Create spot level dataset and 
#add Rel, the residual from subtracting the mel from each value

l3 <- l1[,list(Ligand=unique(Ligand), LigandAnnotID=unique(LigandAnnotID),
               ECMp=unique(ECMp), ECMpAnnotID=unique(ECMpAnnotID),
               MEP=unique(MEP),
               Row=unique(Row), Column = unique(Column), Block=unique(Block), ID=unique(ID),
               ArrayRow=unique(ArrayRow), ArrayColumn=unique(ArrayColumn),
               DNA2Nmel = median(Nuclei_PA_Cycle_DNA2NProportionLogit, na.rm=TRUE),
               SCCmel = as.numeric(median(Spot_PA_SpotCellCount, na.rm=TRUE)),
               Eccmel = median(Nuclei_PA_AreaShape_EccentricityLogit)
),
by="Barcode,Well,Spot"]

if(x[["StainingSet"]] == "SS2"){
  l3$EdUmel <- l1[,list(EdUmel = median(Nuclei_PA_Gated_EduPositiveLogit, na.rm=TRUE)),by=.(Barcode,Well,Spot)][,EdUmel]
  l3 <- l3[, EdURel := calcResidual(EdUmel), by="MEP"]
} else if (unique(x[["StainingSet"]]) == "SS3"){
  l3$LineageRatiomel <- l1[,list(LineageRatiomel = median(Cytoplasm_PA_Intensity_LineageRatio, na.rm=TRUE)),by=.(Barcode,Well,Spot)][,LineageRatiomel]
  l3 <- l3[, LineageRatioRel := calcResidual(LineageRatiomel), by="MEP"]
}

l3 <- l3[, DNA2NRel := calcResidual(DNA2Nmel), by="MEP"]
l3 <- l3[, SCCRel := calcResidual(SCCmel), by="MEP"]
l3 <- l3[, EccRel := calcResidual(Eccmel), by="MEP"]

```

```{r createMatrices}
#For an array  Unit of study there are 64 'samples'of 594 spots with 8 replicates
#Create a spot assignment that recognizes rotated B row arrays
l3$RSpot <- l3$Spot
l3$RSpot[grepl("B",l3$Well)] <- 701-l3$RSpot[grepl("B",l3$Well)]
#Add in ligand and ECMp names so they will carry through the normalization
l3$BWL <- paste(l3$Barcode,l3$Well,l3$Ligand,sep="_")
l3$SE <- paste(l3$RSpot,l3$ECMp,sep="_")
l3$BW <- paste(l3$Barcode,l3$Well,sep="_")
l3$WSE <- paste(l3$Well, l3$RSpot,l3$ECMp,sep="_")

#Cast to get mel values by barcode_well_ligand rows and spot columns
#Coerce missing values to have near 0 values
if(x[["Signal"]] %in% c("EdU", "DNA2N", "Ecc")){
  fill <- log2(.01/(1-.01))
} else if(unique(x[["Signal"]]) %in% c("LineageRatio", "SCC")){
  fill <- 0
} else(stop(paste("Need fill value for",unique(x[["Signal"]])," signal"))) 

```

```{r addResiduals}

l3Relc <- dcast(l3, BWL~SE, value.var=paste0(x[["Signal"]],"Rel"), fill = fill)
#Remove the BWL column and use it as rownames in the matrix
l3Relm <- l3Relc[,grep("BWL",colnames(l3Relc), value=TRUE, invert=TRUE), with=FALSE]
#Y is a numeric matrix of the raw transformed responses 
#of each spot extracted from the l3 dataset
YRelArray <- matrix(unlist(l3Relm), nrow=nrow(l3Relm), dimnames=list(l3Relc$BWL, colnames(l3Relm)))
```


```{r, fig.width=4}

s <- svd(YRelArray)
vDT <- data.table(Value=s$v[,which.max(s$d)], Spot = as.integer(sub("_.*", "",colnames(l3Relm))))
vDT$ArrayRow <- as.integer(ceiling(vDT$Spot/20))
vDT$ArrayColumn <- as.integer((vDT$Spot-1) %% 20 +1)

p <- ggplot(vDT, aes(x=ArrayColumn, y=ArrayRow, fill= Value))+
  geom_tile()+
  scale_fill_gradient(low="white",high="red",oob = scales::squish)+
  ggtitle(bquote(.(x[["Signal"]])~Residual~Maximum~Singular~Value~Eigenvector))+
  xlab("")+ylab("")+
  guides(fill=FALSE)+
  xlim(.5,20.5)+ylim(35.5,.5)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size=rel(.6)), axis.text.y = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(.5)), plot.title = element_text(size = rel(.8)),legend.text=element_text(size = rel(.3)),legend.title=element_text(size = rel(.7)),panel.grid.major = element_line(linetype = 'blank'),panel.background = element_rect(fill = "lightgrey"))
suppressWarnings(print(p))

```

```{r, fig.width=8, fig.height=8}

#Cast to get mel values with Barcode rows and well+Spot+ECMp columns
#Use the names to hold the spot contents
#Coerce missing values to have near 0 proliferation signals
l3Relc <- dcast(l3, Barcode~WSE, value.var=paste0(x[["Signal"]],"Rel"),fill = fill)
#Remove the Barcode column and use it as rownames in the matrix
l3Relm <- l3Relc[,grep("Barcode",colnames(l3Relc), value=TRUE, invert=TRUE), with=FALSE]
YRelPlate <- matrix(unlist(l3Relm), nrow=nrow(l3Relm), dimnames=list(l3Relc$Barcode, colnames(l3Relm)))

s <- svd(YRelPlate)
splits <- strsplit2(colnames(l3Relm), split="_")
vDT <- data.table(Value=s$v[,which.max(s$d)], Well=splits[,1], Spot=as.integer(splits[,2]))
vDT$ArrayRow <- as.integer(ceiling(vDT$Spot/20))
vDT$ArrayColumn <- as.integer((vDT$Spot-1) %% 20 +1)

p <- ggplot(vDT, aes(x=ArrayColumn, y=ArrayRow, fill= Value))+
  geom_tile()+
  scale_fill_gradient(low="white",high="red",oob = scales::squish)+
  ggtitle(bquote(.(x[["Signal"]])~Residual~Maximum~Singular~Value~Eigenvector))+
  xlab("")+ylab("")+
  guides(fill=FALSE)+
  xlim(.5,20.5)+ylim(35.5,.5)+
  facet_wrap(~Well, ncol=4)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size=rel(.6)), axis.text.y = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(.5)), plot.title = element_text(size = rel(.8)),legend.text=element_text(size = rel(.3)),legend.title=element_text(size = rel(.7)),panel.grid.major = element_line(linetype = 'blank'),panel.background = element_rect(fill = "lightgrey"))
suppressWarnings(print(p))


```
