---
output: html_document
---

```{r global_options_Setup, include=FALSE}
#Author: Mark Dane, copyright 2015
knitr::opts_chunk$set(fig.width=12, fig.height=8,
                      echo=FALSE, warning=FALSE, message=FALSE)

#source("MEPLINCSFunctions.R")

library("ggplot2")
library("reshape2")
library("data.table")
library("limma")
library("MEMA")
library("grid")
library("knitr")
library("gplots")
library("RColorBrewer")
library("RUVnormalize")

#Read in file based on name in dataframe
#TODO add staining set to l1 matrix
if(unique(x[["Unit"]])=="StainingSet"){
  l1 <- rbindlist(apply(x, 1, function(xrow){
    l1 <- fread(xrow[["inputFileName"]], showProgress = FALSE)
    #Keep the control wells separate
    l1$Ligand[l1$Ligand=="FBS"] <- paste(l1$Ligand[l1$Ligand=="FBS"],"C",as.numeric(factor(l1$Barcode[l1$Ligand=="FBS"])),sep="")
    l1$StainingSet <- xrow[["StainingSet"]]
    return(l1)
  }), use.names=TRUE, fill=TRUE)
  keepCols <- grep("Cells_|Cytoplasm_|Fibrillarin|Edu|H3|_KRT|Lineage|Endpoint",colnames(l1), invert=TRUE,value=TRUE)
  l1 <- l1[,keepCols,with=FALSE]
} else {
  l1 <- fread(x[["inputFileName"]], showProgress = FALSE)
  #Keep the control wells separate
  l1$Ligand[l1$Ligand=="FBS"] <- paste(l1$Ligand[l1$Ligand=="FBS"],"C",as.numeric(factor(l1$Barcode[l1$Ligand=="FBS"])),sep="")
  
}

l1$MEP <- paste(l1$ECMp,l1$Ligand,sep="_")

#Delete the fiducial and blank spots
l1 <- l1[!grepl("fiducial|Fiducial|blank|PBS",l1$ECMp)]

#Log transform SCC
l1$Spot_PA_SpotCellCountLog2 <- log2(l1$Spot_PA_SpotCellCount)

#Logit transform DNA2NProportion
#logit(p) = log[p/(1-p)]
DNA2NImpute <- l1$Nuclei_PA_Cycle_DNA2NProportion
DNA2NImpute[DNA2NImpute==0] <- .01
DNA2NImpute[DNA2NImpute==1] <- .99
l1$Nuclei_PA_Cycle_DNA2NProportionLogit <- log2(DNA2NImpute/(1-DNA2NImpute))

#logit transform eccentricity
EccImpute <- l1$Nuclei_CP_AreaShape_Eccentricity
EccImpute[EccImpute==0] <- .01
EccImpute[EccImpute==1] <- .99
l1$Nuclei_PA_AreaShape_EccentricityLogit <- log2(EccImpute/(1-EccImpute))


#Create spot level dataset and 
#add Rel, the residual from subtracting the mel from each value

l3 <- l1[,list(Ligand=unique(Ligand), LigandAnnotID=unique(LigandAnnotID),
               ECMp=unique(ECMp), ECMpAnnotID=unique(ECMpAnnotID),
               MEP=unique(MEP),
               #StainingSet=unique(StainingSet), #remove after Staining Set is in l1
               Row=unique(Row), Column = unique(Column), Block=unique(Block), ID=unique(ID),
               ArrayRow=unique(ArrayRow), ArrayColumn=unique(ArrayColumn),
               DNA2Nmel = median(Nuclei_PA_Cycle_DNA2NProportionLogit, na.rm=TRUE),
               SCCmel = as.numeric(median(Spot_PA_SpotCellCountLog2, na.rm=TRUE)),
               Eccmel = median(Nuclei_PA_AreaShape_EccentricityLogit)
),
by="Barcode,Well,Spot"]
l3 <- l3[, SCCRel := calcResidual(SCCmel), by="MEP"]
l3 <- l3[, EccRel := calcResidual(Eccmel), by="MEP"]
l3 <- l3[, DNA2NRel := calcResidual(DNA2Nmel), by="MEP"]

if(!any(!x[["StainingSet"]] == "SS2")){
  l3$EdUmel <- l1[,list(EdUmel = median(Nuclei_PA_Gated_EduPositiveLogit, na.rm=TRUE)),by=.(Barcode,Well,Spot)][,EdUmel]
  l3 <- l3[, EdURel := calcResidual(EdUmel), by="MEP"]
} else if (!any(!x[["StainingSet"]] == "SS3")){
  l3$LineageRatioLog2mel <- l1[,list(LineageRatioLog2mel = median(Cytoplasm_PA_Intensity_LineageRatioLog2, na.rm=TRUE)),by=.(Barcode,Well,Spot)][,LineageRatioLog2mel]
  l3 <- l3[, LineageRatioLog2Rel := calcResidual(LineageRatioLog2mel), by="MEP"]
}
l3$LigandAnnotID <- sub("_","-",l3$LigandAnnotID)
l3$Ligand <- sub("_","-",l3$Ligand)

l1MEPs <- l3[,list(mel = median(eval(parse(text=paste0(unique(unique(x[["Signal"]])),"mel")))),
                   Mel = mad(eval(parse(text=paste0(unique(x[["Signal"]]),"mel"))))),
             by="Barcode,Well,Ligand,ECMp,MEP"]
#l1MEPS is the data.table of the MEP level, raw, transformed responses
l1MEPs <- addMarginValues(l1MEPs,"mel","Mel")

#calculate the overall median and MAD for the staining set
m.. <- median(l1MEPs$mel, na.rm = TRUE)
M.. <- median(l1MEPs$Mel, na.rm = TRUE)

```

```{r createMatrices}
#For an array  Unit of study there are 64 'samples'of 594 spots with 8 replicates
#Create a spot assignment that recognizes rotated B row arrays
l3$RSpot <- l3$Spot
l3$RSpot[grepl("B",l3$Well)] <- 701-l3$RSpot[grepl("B",l3$Well)]
#Add in ligand and ECMp names so they will carry through the normalization
l3$BWL <- paste(l3$Barcode,l3$Well,l3$Ligand,sep="_")
l3$SE <- paste(l3$RSpot,l3$ECMp,sep="_")
l3$BW <- paste(l3$Barcode,l3$Well,sep="_")
l3$WSE <- paste(l3$Well, l3$RSpot,l3$ECMp,sep="_")
l3$BWLSE <- paste(l3$Barcode, l3$Well, l3$Ligand, l3$RSpot,l3$ECMp,sep="_")
l3$StainingSet <- x[["StainingSet"]]

#Cast to get mel values by barcode_well_ligand rows and spot columns
#logit transform the values that are porportions in the [0,1] range
#Coerce missing values to have near 0 values before transformation
if(unique(unique(x[["Signal"]])) %in% c("EdU", "DNA2N", "Ecc")){
  fill <- log2(.01/(1-.01))
} else if(unique(x[["Signal"]]) %in% c("SCC")){
  fill <- 1
} else if(unique(x[["Signal"]]) %in% c("LineageRatioLog2")){
  fill <- log2(.001)
} else(stop(paste("Need fill value for",unique(x[["Signal"]])," signal"))) 

l3c <- dcast(l3, BWL~SE, value.var=paste0(unique(x[["Signal"]]),"mel"), fill = fill)
#Remove the BWL column and use it as rownames in the matrix
l3m <- l3c[,grep("BWL",colnames(l3c), value=TRUE, invert=TRUE), with=FALSE]
#Y is a numeric matrix of the raw transformed responses 
#of each spot extracted from the l3 dataset
YArray <- matrix(unlist(l3m), nrow=nrow(l3m), dimnames=list(l3c$BWL, colnames(l3m)))

if(x[["Unit"]]=="ArrayWithResiduals"){
  l3c <- dcast(l3, BWL~SE, value.var=paste0(unique(x[["Signal"]]),"Rel"), fill = fill)
  #Remove the BWL column and use it as rownames in the matrix
  l3m <- l3c[,grep("BWL",colnames(l3c), value=TRUE, invert=TRUE), with=FALSE]
  #Y is a numeric matrix of the raw transformed responses 
  #of each spot extracted from the l3 dataset
  YArrayResiduals <- matrix(unlist(l3m), nrow=nrow(l3m), dimnames=list(l3c$BWL, colnames(l3m)))
  YArrayVR <-cbind(YArray,YArrayResiduals)
}
#Setup data with plate as the unit
#There are 8 'samples' with 694 controls
#Order the spot level data by plate, well, spot number

#Cast to get mel values with Barcode rows and well+Spot+ECMp columns
#Use the names to hold the spot contents
#Coerce missing values to have near 0 proliferation signals
l3PlateC <- dcast(l3, Barcode~WSE, value.var=paste0(unique(x[["Signal"]]),"mel"),fill = fill)
#Remove the Barcode column and use it as rownames in the matrix
l3m <- l3PlateC[,grep("Barcode",colnames(l3PlateC), value=TRUE, invert=TRUE), with=FALSE]
YPlate <- matrix(unlist(l3m), nrow=nrow(l3m), dimnames=list(l3PlateC$Barcode, colnames(l3m)))

#Set up data with staining set as the unit, 3x44416
#Cast to get mel values with Staining Set rows and Barcode+well+Spot+ECMp columns
#Use the names to hold the spot contents
#Coerce missing values to have near 0 proliferation signals
l3ssC <- dcast(l3, StainingSet~BWLSE, value.var=paste0(unique(x[["Signal"]]),"mel"), fill = fill)
l3m <- l3ssC[,grep("StainingSet",colnames(l3ssC), value=TRUE, invert=TRUE), with=FALSE]
Yss <- matrix(unlist(l3m), nrow=nrow(l3m), dimnames=list(l3ssC$StainingSet, colnames(l3m)))

```

---
title: "MEP-LINCS `r x[["CellLine"]]`  `r x[["StainingSet"]]`  `r unique(x[["Signal"]])` `r unique(x[["Method"]])`  `r unique(x[["Unit"]])` Normalization"
date: "`r Sys.Date()`"
---


```{r, eval=TRUE, fig.width=4.5, fig.height=4}

limits=quantile(l1MEPs[["mel"]], probs=c(.005, .995), na.rm=TRUE)
titleExpression <- bquote(.(unique(x[["Signal"]]))~Medians~(m["e,l"]))
plotLEHmap(l1MEPs, fill="mel", titleExpression, limits)

limits=quantile(l1MEPs[["Mel"]], probs=c(.005, .995), na.rm=TRUE)
titleExpression <- bquote(.(unique(x[["Signal"]]))~MADs~(M["e,l"]))
plotLEHmap(l1MEPs, fill="Mel", titleExpression, limits)

```


```{r, child='NaiveRandRUVText.Rmd', eval=unique(x[["Method"]])=="NaiveRandRUV"}
```


```{r, child='NaiveReplicateRUVVRText.Rmd', eval=unique(x[["Method"]])=="NaiveReplicateRUV" & unique(x[["Unit"]])=="ArrayWithResiduals"}
```

```{r, child='NaiveReplicateRUVText.Rmd', eval=unique(x[["Method"]])=="NaiveReplicateRUV" & unique(x[["Unit"]])=="Array"}
```


```{r, child='NaiveReplicateRUVSSText.Rmd', eval=unique(x[["Method"]])=="NaiveReplicateRUVSS"}
```


```{r, child='RUV3Text.Rmd', eval=unique(x[["Method"]])=="RUV3" & unique(x[["Unit"]])=="Plate"}
```



```{r, child='RUV3ResText.Rmd', eval=unique(x[["Method"]])=="RUV3" & unique(x[["Unit"]])=="ArrayWithResiduals"}
```


```{r, eval=unique(x[["Method"]])=="RZS"}

nYm <- medianRZS(YPlate)
setnames(nYm, "Value", "mel")
nYM <- madRZS(YPlate)
setnames(nYM, "Value", "Mel")
setkey(nYm,Barcode,Well,ECMp)
setkey(nYM,Barcode,Well,ECMp)
nY <- merge(nYm, nYM)
nY$BW <- paste(nY$Barcode,nY$Well, sep="_")
setkey(nY,BW)
BWL <- unique(l3[,.(BW,Ligand)])
setkey(BWL,BW)
nY <- merge(nY, BWL)
nY$MEP <- paste(nY$ECMp,nY$Ligand, sep="_")
nY <- nY[,BW :=NULL]
#Add margin values
nY <- addMarginValues(dt=nY, mValue="mel",MValue="Mel")


```

```{r, eval=unique(x[["Method"]])=="NaiveReplicateRUV" & unique(x[["Unit"]])=="Array"}

#Set up replicate index matrix with A03 wells as replicates
replicateWells <- which(grepl("A03",rownames(YArray)))
scIdx <- matrix(-1, 57, 8)
c <- 1
scIdx[1,] <- replicateWells

for (r in 1:nrow(YArray)){
  if(r %in% replicateWells)
    next
  c <- c+1
  scIdx[c,1] <- r
}


nYkList <- lapply(0:7, function(k, Y, cIdx, scIdx, mValue, MValue){
  #Normalize the spot level data then median summarize
  nYm <- medianNaiveReplicateRUV2(k, Y, cIdx, scIdx)
  setnames(nYm, "Value", "mel")
  #Normalize the spot level data then MAD summarize
  nYM <- madNaiveReplicateRUV2(k, Y, cIdx, scIdx)
  setnames(nYM, "Value", "Mel")
  setkey(nYm,Barcode,MEP,ECMp,Ligand,Well)
  setkey(nYM, Barcode,MEP,ECMp,Ligand,Well)
  nY <- merge(nYm, nYM)
  #Add margin values
  nY <- addMarginValues(dt=nY, mValue="mel",MValue="Mel")
  nY$k <- k
  return(nY)
}, Y=YArray, cIdx=1:ncol(YArray), scIdx=scIdx, mValue="mel", MValue="Mel")

nY <- rbindlist(nYkList)

```


```{r, eval=unique(x[["Method"]])=="NaiveReplicateRUV" & unique(x[["Unit"]])=="ArrayWithResiduals"}

#Set up replicate index matrix with A03 wells as replicates
replicateWells <- which(grepl("A03",rownames(YArrayVR)))
scIdx <- matrix(-1, 57, 8)
c <- 1
scIdx[1,] <- replicateWells

for (r in 1:nrow(YArrayVR)){
  if(r %in% replicateWells)
    next
  c <- c+1
  scIdx[c,1] <- r
}

#Hardcode in identification of residuals as the controls
resStart <- ncol(YArrayVR)/2+1
cIdx=resStart:ncol(YArrayVR)


nYkList <- lapply(0:7, function(k, Y, cIdx, scIdx, mValue, MValue){
  #Normalize the spot level data then median summarize
  nYm <- medianNaiveReplicateRUV2(k, Y, cIdx, scIdx)
  setnames(nYm, "Value", "mel")
  #Normalize the spot level data then MAD summarize
  nYM <- madNaiveReplicateRUV2(k, Y, cIdx, scIdx)
  setnames(nYM, "Value", "Mel")
  setkey(nYm,Barcode,MEP,ECMp,Ligand,Well)
  setkey(nYM, Barcode,MEP,ECMp,Ligand,Well)
  nY <- merge(nYm, nYM)
  #Add margin values
  nY <- addMarginValues(dt=nY, mValue="mel",MValue="Mel")
  nY$k <- k
  return(nY)
}, Y=YArrayVR, cIdx=cIdx, scIdx=scIdx, mValue="mel", MValue="Mel")

nY <- rbindlist(nYkList)

```

```{r, eval=unique(x[["Method"]])=="NaiveReplicateRUVSS"}

#Set up replicate index matrix with A03 wells as replicates
scIdx <- matrix(1:3, 1, 3)

cIdx=which(grepl("A03",colnames(Yss)))

nYkList <- lapply(0:2, function(k, Y, cIdx, scIdx, mValue, MValue){
  #Normalize the spot level data then median summarize
  nYm <- medianNaiveReplicateRUV2SS(k, Y, cIdx, scIdx)
  setnames(nYm, "Value", "mel")
  #Normalize the spot level data then MAD summarize
  #Debug fails here, may be due to Y being a data.table
  nYM <- madNaiveReplicateRUV2SS(k, Y, cIdx, scIdx)
  setnames(nYM, "Value", "Mel")
  setkey(nYm, StainingSet,Barcode,MEP,ECMp,Ligand,Well)
  setkey(nYM, StainingSet,Barcode,MEP,ECMp,Ligand,Well)
  nY <- merge(nYm, nYM)
  #Add margin values
  nY <- addMarginValues(dt=nY, mValue="mel",MValue="Mel")
  nY$k <- k
  return(nY)
}, Y=Yss, cIdx=cIdx, scIdx=scIdx, mValue="mel", MValue="Mel")

nY <- rbindlist(nYkList)

```

```{r, eval=unique(x[["Method"]])=="NaiveRandRUV"}

nYknList <- lapply(c(0,2,3,4,5), function(k, YPlate, cIdx, mValue, MValue){
  nuYList <- lapply(c(1e-2,1e-1,1), function(nu, k, Y, cIdx, mValue, MValue){
    #browser()
    nYm <- medianNaiveRUV2Plate(nu, Y, cIdx, k)
    setnames(nYm, "Value", "mel")
    nYM <- madNaiveRUV2Plate(nu, Y, cIdx, k)
    setnames(nYM, "Value", "Mel")
    setkey(nYm,Barcode,Well,ECMp)
    setkey(nYM,Barcode,Well,ECMp)
    nY <- merge(nYm, nYM)
    nY$BW <- paste(nY$Barcode,nY$Well, sep="_")
    setkey(nY,BW)
    BWL <- unique(l3[,.(BW,Ligand)])
    setkey(BWL,BW)
    nY <- merge(nY, BWL)
    nY$MEP <- paste(nY$ECMp,nY$Ligand, sep="_")
    nY <- nY[,BW :=NULL]
    
    #Add margin values
    nY <- addMarginValues(dt=nY, mValue="mel",MValue="Mel")
    nY$k <- k
    nY$nu <- nu
    return(nY)
  }, k=k, Y=YPlate, cIdx=cIdx, mValue="mel", MValue="Mel")
  vnuYDT <- rbindlist(nuYList)
}, YPlate=YPlate, cIdx=which(grepl("A03",colnames(YPlate))), mValue="mel", MValue="Mel")

nY <- rbindlist(nYknList)

```

```{r, eval=unique(x[["Method"]])=="RUV3" & unique(x[["Unit"]])=="Array"}

nYkList <- lapply(0:5, function(k, Y, M, cIdx, mValue, MValue){
  #browser()
  nYm <- medianRUVIIIPlate(k, Y, M, cIdx)
  setnames(nYm, "Value", "mel")
  nYM <- madRUVIIIPlate(k, Y, M, cIdx)
  setnames(nYM, "Value", "Mel")
  setkey(nYm,Barcode,Well,ECMp)
  setkey(nYM,Barcode,Well,ECMp)
  nY <- merge(nYm, nYM)
  nY$BW <- paste(nY$Barcode,nY$Well, sep="_")
  setkey(nY,BW)
  BWL <- unique(l3[,.(BW,Ligand)])
  setkey(BWL,BW)
  nY <- merge(nY, BWL)
  nY$MEP <- paste(nY$ECMp,nY$Ligand, sep="_")
  nY <- nY[,BW :=NULL]
  
  #Add margin values
  nY <- addMarginValues(dt=nY, mValue="mel",MValue="Mel")
  nY$k <- k
  return(nY)
}, Y=YPlate, M=matrix(1,nrow=nrow(YPlate)), cIdx=which(grepl("A03",colnames(YPlate))), mValue="mel", MValue="Mel")

nY <- rbindlist(nYkList)

```


```{r normRUV3ArrayResiduals, eval=unique(x[["Method"]])=="RUV3" & unique(x[["Unit"]])=="ArrayWithResiduals"}

#Set up the M Matrix to denote replicates
nrControlWells <- sum(grepl("FBS",rownames((YArrayVR))))
nrLigandWells <- dim(YArrayVR)[1]-nrControlWells
M <-matrix(0, nrow = dim(YArrayVR)[1], ncol = nrLigandWells+1)
rownames(M) <- rownames(YArrayVR)
#Indicate the control wells in the last column
Mc <- M[grepl("FBS",rownames(M)),]
Mc[,ncol(Mc)] <-1L
#Subset to the ligand wells and mark as non-replicate
Ml <- M[!grepl("FBS",rownames(M)),]
for(i in 1:nrLigandWells) Ml[i,i] <- 1
#Add the replicate wells and restore the row order
M <- rbind(Mc,Ml)
M <- M[order(rownames(M)),]

#Hardcode in identification of residuals as the controls
resStart <- ncol(YArrayVR)/2+1
cIdx=resStart:ncol(YArrayVR)

nYkList <- lapply(c(0,7), function(k, Y, M, cIdx, mValue, MValue){
  nYm <- medianRUVIIIArrayWithResiduals(k, Y, M, cIdx) #Normalize the spot level data then median summarize
  setnames(nYm, "Value", "mel")
  #Normalize the spot level data then MAD summarize
  nYM <- madRUVIIIArrayWithResiduals(k, Y, M, cIdx)
  setnames(nYM, "Value", "Mel")
  setkey(nYm,Barcode,ECMp,Well,Ligand,MEP)
  setkey(nYM, Barcode,ECMp,Well,Ligand,MEP)
  nY <- merge(nYm, nYM)
  #Add margin values
  nY <- addMarginValues(dt=nY, mValue="mel",MValue="Mel")
  nY$k <- k
  return(nY)
}, Y=YArrayVR, cIdx=cIdx, M=M, mValue="mel", MValue="Mel")

nY <- rbindlist(nYkList)

nYSkList <- lapply(c(0,7), function(k, Y, M, cIdx, mValue, MValue){
  nY <- RUVIIIArrayWithResiduals(k, Y, M, cIdx) #Normalize the spot level data
  nY$k <- k
  return(nY)
}, Y=YArrayVR, cIdx=cIdx, M=M, mValue="mel", MValue="Mel")
nYS <- rbindlist(nYSkList)

#Add back Array row and column values
nrRows <- max(l1$ArrayRow)
nrCols <- max(l1$ArrayColumn)
nYS$ArrayColumn <- (nYS$Spot-1) %% nrCols+1
nYS$ArrayRow <- ceiling(nYS$Spot/20)

```

```{r plotECMBoxes, fig.height=10,fig.width=8.5}
groupBy <- "ECMp"
value <- "mel-m.l"
colourBy <- "Barcode"

yLimits=quantile(nY[["mel"]]-nY[["m.l"]], probs=c(.001, .999), na.rm=TRUE)
p <- ggplot(nY,aes_string(x=groupBy, y=value))+
  geom_boxplot()+ 
  ggtitle(bquote(.(unique(x[["Signal"]]))~Medians~(m["e,l"]*"-"*m[".,l"])~After~.(unique(x[["Method"]]))~Normalization~with~.(unique(x[["Unit"]]))~Unit))+
  xlab("")+ylab("")+
  coord_cartesian(ylim=yLimits)+
  guides(fill=FALSE)+
  theme_grey(base_size = 12, base_family = "")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size=rel(.6)), axis.text.y = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(1)), plot.title = element_text(size = rel(1)),legend.text=element_text(size = rel(.3)),legend.title=element_text(size = rel(.5)))

if(unique(x[["Method"]]) %in% c("NaiveRandRUV")){
  p <- p +  facet_grid(k~nu, labeller = labeller(nu = label_both, k = label_both))
} else if (unique(x[["Method"]]) %in% c("NaiveReplicateRUV","RUV3","NaiveReplicateRUVSS")) {
  p <- p + facet_grid(k~., labeller = labeller(k = label_both))
} else if (unique(x[["Method"]]) %in% c("RZS")) {
  p <- p
}  else(stop(paste("Do not have a plot method for",unique(x[["Method"]]),"normalization")))

suppressWarnings(print(p))

```

```{r plotLigandBoxes, fig.height=10}
groupBy <- "Ligand"
value <- "mel-me."
colourBy <- "Barcode"

yLimits=quantile(nY[["mel"]]-nY[["me."]], probs=c(.001, .991), na.rm=TRUE)

p <- ggplot(nY,aes_string(x=groupBy, y=value, colour=colourBy))+
  geom_boxplot()+ 
  ggtitle(bquote(.(unique(x[["Signal"]]))~Medians~(m["e,l"]*"-"*m["e,."])~After~.(unique(x[["Method"]]))~Normalization~with~.(unique(x[["Unit"]]))~Unit))+
  xlab("")+ylab("")+
  coord_cartesian(ylim=yLimits)+
  guides(fill=FALSE)+
  theme_grey(base_size = 12, base_family = "")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size=rel(.6)), axis.text.y = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(1)), plot.title = element_text(size = rel(1)),legend.text=element_text(size = rel(.3)),legend.title=element_text(size = rel(.5)))

if(unique(x[["Method"]]) %in% c("NaiveRandRUV")){
  p <- p +  facet_grid(k~nu, labeller = labeller(nu = label_both, k = label_both))
} else if (unique(x[["Method"]]) %in% c("NaiveReplicateRUV","RUV3","NaiveReplicateRUVSS")) {
  p <- p + facet_grid(k~., labeller = labeller(k = label_both))
} else if (unique(x[["Method"]]) %in% c("RZS")) {
  p <- p
}  else(stop(paste("Do not have a plot method for",unique(x[["Method"]]),"normalization")))
suppressWarnings(print(p))

groupBy <- "Barcode"
value <- "mel-me."
colourBy <- "Well"

p <- ggplot(nY,aes_string(x=groupBy, y=value, colour=colourBy))+
  geom_boxplot()+ 
  ggtitle(bquote(.(unique(x[["Signal"]]))~Medians~(m["e,l"]*"-"*m["e,."])~After~.(unique(x[["Method"]]))~Normalization~with~.(unique(x[["Unit"]]))~Unit))+
  xlab("")+ylab("")+
  coord_cartesian(ylim=yLimits)+
  guides(fill=FALSE)+
  theme_grey(base_size = 12, base_family = "")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size=rel(.6)), axis.text.y = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(1)), plot.title = element_text(size = rel(1)),legend.text=element_text(size = rel(.3)),legend.title=element_text(size = rel(.5)))

if(unique(x[["Method"]]) %in% c("NaiveRandRUV")){
  p <- p +  facet_grid(k~nu, labeller = labeller(nu = label_both, k = label_both))
} else if (unique(x[["Method"]]) %in% c("NaiveReplicateRUV","RUV3","NaiveReplicateRUVSS")) {
  p <- p + facet_grid(k~., labeller = labeller(k = label_both))
} else if (unique(x[["Method"]]) %in% c("RZS")) {
  p <- p
}  else(stop(paste("Do not have a plot method for",unique(x[["Method"]]),"normalization")))
suppressWarnings(print(p))

```


```{r normRUV3ArrayResiduals1stLoess, eval=unique(x[["Method"]])=="RUV3" & unique(x[["Unit"]])=="ArrayWithResiduals"}

#' Loess normalize an array using the biological residuals
#' @export
loessNorm <- function(Value,Residual,ArrayRow,ArrayColumn){
  dt <-data.table(Value=Value,Residual=Residual,ArrayRow=ArrayRow,ArrayColumn=ArrayColumn)
  lm <- loess(Residual~ArrayRow+ArrayColumn, dt, span=.7)
  dt$ResidualLoess<-predict(lm)
  dt <- dt[,ValueLoess := Value-ResidualLoess]
  return(ValueLoess = dt$ValueLoess)
}

loessNormArrays <- function(dt){
  #Loess normalize values within an array
  #Get the spot mean over all arrays
  dt <- dt[,mel :=mean(Value),by="MEP"]
  #Get the residuals from the spot mean
  dt <- dt[,Residual := Value-mel]
  #Subtract the loess model of each array's residuals from the signal
  dt <- dt[, ValueLoess:= loessNorm(Value,Residual,ArrayRow,ArrayColumn), by="BWL"]
  dt$ValueLoess[dt$k==0] <- dt$Value
  return(dt)
}

#Loess normalize and return spot level data
lnY <- rbindlist(lapply(unique(nYS$k), function(kValue, nYS){
  #Get one dataset for one k value
  dt <- nYS[nYS$k==kValue,]
  dt <- loessNormArrays(dt)
  dt$k <- kValue
  #dt is RUV3 normalized and Loess normalized spot level data
  return(dt)
}, nYS=nYS)) #

#Summarize loess normed to MEP level to get mel values
lnYMep <- lnY[,list(Barcode=unique(Barcode),ECMp=unique(ECMp),Ligand=unique(Ligand), Well=unique(Well), mel=median(ValueLoess),Mel=mad(ValueLoess, na.rm=TRUE)), by="MEP,k"]

#add margin values me., m.l, Me. and Ml. for each k value
lnYMep <- rbindlist(lapply(unique(lnYMep$k), function(kValue, dt){
  dt <- dt[dt$k==kValue]
  dt <- addMarginValues(dt, mValue="mel",MValue="Mel")
  return(dt)
}, dt=lnYMep))

```

```{r plotAfter1stRUVLoess, , eval=unique(x[["Method"]])=="RUV3" & unique(x[["Unit"]])=="ArrayWithResiduals"}

groupBy <- "ECMp"
value <- "mel-m.l"
colourBy <- "Barcode"

yLimits=quantile(lnYMep[["mel"]]-lnYMep[["m.l"]], probs=c(.001, .999), na.rm=TRUE)
p <- ggplot(lnYMep,aes_string(x=groupBy, y=value))+
  geom_boxplot()+ 
  ggtitle(bquote(.(unique(x[["Signal"]]))~Medians~(m["e,l"]*"-"*m[".,l"])~After~.(unique(x[["Method"]]))~and~loess~Normalization~with~.(unique(x[["Unit"]]))~Unit))+
  xlab("")+ylab("")+
  coord_cartesian(ylim=yLimits)+
  guides(fill=FALSE)+
  theme_grey(base_size = 12, base_family = "")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size=rel(.6)), axis.text.y = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(1)), plot.title = element_text(size = rel(1)),legend.text=element_text(size = rel(.3)),legend.title=element_text(size = rel(.5)))

if(unique(x[["Method"]]) %in% c("NaiveRandRUV")){
  p <- p +  facet_grid(k~nu, labeller = labeller(nu = label_both, k = label_both))
} else if (unique(x[["Method"]]) %in% c("NaiveReplicateRUV","RUV3","NaiveReplicateRUVSS")) {
  p <- p + facet_grid(k~., labeller = labeller(k = label_both))
} else if (unique(x[["Method"]]) %in% c("RZS")) {
  p <- p
}  else(stop(paste("Do not have a plot method for",unique(x[["Method"]]),"normalization")))

suppressWarnings(print(p))

groupBy <- "Ligand"
value <- "mel-me."
colourBy <- "Barcode"

yLimits=quantile(lnYMep[["mel"]]-lnYMep[["me."]], probs=c(.001, .991), na.rm=TRUE)

p <- ggplot(lnYMep,aes_string(x=groupBy, y=value, colour=colourBy))+
  geom_boxplot()+ 
  ggtitle(bquote(.(unique(x[["Signal"]]))~Medians~(m["e,l"]*"-"*m["e,."])~After~.(unique(x[["Method"]]))~and ~loess~Normalization~with~.(unique(x[["Unit"]]))~Unit))+
  xlab("")+ylab("")+
  coord_cartesian(ylim=yLimits)+
  guides(fill=FALSE)+
  theme_grey(base_size = 12, base_family = "")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size=rel(.6)), axis.text.y = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(1)), plot.title = element_text(size = rel(1)),legend.text=element_text(size = rel(.3)),legend.title=element_text(size = rel(.5)))

if(unique(x[["Method"]]) %in% c("NaiveRandRUV")){
  p <- p +  facet_grid(k~nu, labeller = labeller(nu = label_both, k = label_both))
} else if (unique(x[["Method"]]) %in% c("NaiveReplicateRUV","RUV3","NaiveReplicateRUVSS")) {
  p <- p + facet_grid(k~., labeller = labeller(k = label_both))
} else if (unique(x[["Method"]]) %in% c("RZS")) {
  p <- p
}  else(stop(paste("Do not have a plot method for",unique(x[["Method"]]),"normalization")))
suppressWarnings(print(p))

groupBy <- "Barcode"
value <- "mel-me."
colourBy <- "Well"

p <- ggplot(lnYMep,aes_string(x=groupBy, y=value, colour=colourBy))+
  geom_boxplot()+ 
  ggtitle(bquote(.(unique(x[["Signal"]]))~Medians~(m["e,l"]*"-"*m["e,."])~After~.(unique(x[["Method"]]))~and~ loess~Normalization~with~.(unique(x[["Unit"]]))~Unit))+
  xlab("")+ylab("")+
  coord_cartesian(ylim=yLimits)+
  guides(fill=FALSE)+
  theme_grey(base_size = 12, base_family = "")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size=rel(.6)), axis.text.y = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(1)), plot.title = element_text(size = rel(1)),legend.text=element_text(size = rel(.3)),legend.title=element_text(size = rel(.5)))

if(unique(x[["Method"]]) %in% c("NaiveRandRUV")){
  p <- p +  facet_grid(k~nu, labeller = labeller(nu = label_both, k = label_both))
} else if (unique(x[["Method"]]) %in% c("NaiveReplicateRUV","RUV3","NaiveReplicateRUVSS")) {
  p <- p + facet_grid(k~., labeller = labeller(k = label_both))
} else if (unique(x[["Method"]]) %in% c("RZS")) {
  p <- p
}  else(stop(paste("Do not have a plot method for",unique(x[["Method"]]),"normalization")))
suppressWarnings(print(p))

```

```{r, secondRUV3onResiduals, eval=FALSE}
#create a signal+residual matrix
#Remove the raw data
lnY <- lnY[!lnY$k==0,]
#Create a matrix of the signal values
lnYVc <- dcast(lnY, BWL~SE, value.var="ValueLoess", fill = fill)
#Remove the BWL column and use it as rownames in the matrix
lnYVcm <- lnYVc[,grep("BWL",colnames(lnYVc), value=TRUE, invert=TRUE), with=FALSE]
lnYVcm <- matrix(unlist(lnYVcm), nrow=nrow(lnYVcm), dimnames=list(lnYVc$BWL, colnames(lnYVcm)))

#Y is a numeric matrix of the raw transformed responses 
#of each spot extracted from the l3 dataset
lnYResiduals <- matrix(unlist(lnYm), nrow=nrow(lnYm), dimnames=list(lnYc$BWL, colnames(lnYm)))
#Add residuals from the biological values
lnY <- lnY[,Rel := calcResidual(ValueLoess), by="MEP"]
setnames(lnY,"Rel",paste0(x[["Signal"]],"Rel"))
lnYc <- dcast(lnY, BWL~SE, value.var=paste0(unique(x[["Signal"]]),"Rel"), fill = fill)

#Remove the BWL column and use it as rownames in the matrix
lnYm <- lnYc[,grep("BWL",colnames(lnYc), value=TRUE, invert=TRUE), with=FALSE]
#Y is a numeric matrix of the raw transformed responses 
#of each spot extracted from the l3 dataset
lnYResiduals <- matrix(unlist(lnYm), nrow=nrow(lnYm), dimnames=list(lnYc$BWL, colnames(lnYm)))
lnYVR <-cbind(lnYVcm,lnYResiduals)

lnYSk <- rbindlist(lapply(c(0,7), function(k, Y, M, cIdx, mValue, MValue){
  nY <- RUVIIIArrayWithResiduals(k, Y, M, cIdx) #Normalize the spot level data
  nY$k <- k
  return(nY)
}, Y=lnYVR, cIdx=cIdx, M=M, mValue="mel", MValue="Mel"))


#Add back Array row and column values
nrRows <- max(l1$ArrayRow)
nrCols <- max(l1$ArrayColumn)
nYS$ArrayColumn <- (nYS$Spot-1) %% nrCols+1
nYS$ArrayRow <- ceiling(nYS$Spot/20)

```

```{r plotPCA, fig.height=10,fig.width=8.5, eval=FALSE}
groupBy <- "ECMp"
value <- "Value"
colourBy <- "Barcode"

p <- ggplot(nYS,aes_string(x=groupBy, y=value))+
  geom_boxplot()+ 
  ggtitle(bquote(~Spot~Level~.(unique(x[["Signal"]]))~After~.(unique(x[["Method"]]))~Normalization~with~.(unique(x[["Unit"]]))~Unit))+
  xlab("")+ylab("")+
  #coord_cartesian(ylim=yLimits)+
  guides(fill=FALSE)+
  theme_grey(base_size = 12, base_family = "")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size=rel(.6)), axis.text.y = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(1)), plot.title = element_text(size = rel(1)),legend.text=element_text(size = rel(.3)),legend.title=element_text(size = rel(.5)))

if(unique(x[["Method"]]) %in% c("NaiveRandRUV")){
  p <- p +  facet_grid(k~nu, labeller = labeller(nu = label_both, k = label_both))
} else if (unique(x[["Method"]]) %in% c("NaiveReplicateRUV","RUV3","NaiveReplicateRUVSS")) {
  p <- p + facet_grid(k~., labeller = labeller(k = label_both))
} else if (unique(x[["Method"]]) %in% c("RZS")) {
  p <- p
}  else(stop(paste("Do not have a plot method for",unique(x[["Method"]]),"normalization")))

suppressWarnings(print(p))

groupBy <- "Ligand"
value <- "Value"
colourBy <- "Barcode"

#ToDo summarize back to MEP level, calculate margins and subtract

groupBy <- "Ligand"
value <- "ValueLoess"
colourBy <- "Barcode"

p <- ggplot(nnYs,aes_string(x=groupBy, y=value, colour=colourBy))+
  geom_boxplot()+ 
  ggtitle(bquote(~Spot~Level~.(unique(x[["Signal"]]))~After~.(unique(x[["Method"]]))~Normalization~with~.(unique(x[["Unit"]]))~Unit))+
  xlab("")+ylab("")+
  #coord_cartesian(ylim=yLimits)+
  guides(fill=FALSE)+
  theme_grey(base_size = 12, base_family = "")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size=rel(.6)), axis.text.y = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(1)), plot.title = element_text(size = rel(1)),legend.text=element_text(size = rel(.3)),legend.title=element_text(size = rel(.5)))

if(unique(x[["Method"]]) %in% c("NaiveRandRUV")){
  p <- p +  facet_grid(k~nu, labeller = labeller(nu = label_both, k = label_both))
} else if (unique(x[["Method"]]) %in% c("NaiveReplicateRUV","RUV3","NaiveReplicateRUVSS")) {
  p <- p + facet_grid(k~., labeller = labeller(k = label_both))
} else if (unique(x[["Method"]]) %in% c("RZS")) {
  p <- p
}  else(stop(paste("Do not have a plot method for",unique(x[["Method"]]),"normalization")))

suppressWarnings(print(p))

nYsPCA <- princomp(~Value, data=nYS)


```
